//Common Services
export const COUNTRIES_PHONECODES_LIST = 'COUNTRIES_PHONECODES_LIST';
export const COUNTRIES_PHONECODES_LIST_SUCCESS = 'COUNTRIES_PHONECODES_LIST_SUCCESS';
export const USER_STATUS_CHANGE = 'USER_STATUS_CHANGE';
export const USER_STATUS_CHANGE_SUCCESS = 'USER_STATUS_CHANGE_SUCCESS';
export const COUNTRY_LIST = 'COUNTRY_LIST';
export const COUNTRY_LIST_SUCCESS = 'COUNTRY_LIST_SUCCESS';
export const ADMIN_USER_DETAILS_GET = 'ADMIN_USER_DETAILS_GET';
export const ADMIN_USER_DETAILS_GET_SUCCESS = 'ADMIN_USER_DETAILS_GET_SUCCESS';

//Compose Message
export const COMPOSE_SMS_ACTION = 'COMPOSE_SMS_ACTION';
export const COMPOSE_SMS_SUCCESS = 'COMPOSE_SMS_SUCCESS';
export const COMPOSE_EMAIL_ACTION = 'COMPOSE_EMAIL_ACTION';
export const COMPOSE_EMAIL_SUCCESS = 'COMPOSE_EMAIL_SUCCESS';
export const COMPOSE_VOICEMAIL_ACTION = 'COMPOSE_VOICEMAIL_ACTION';
export const COMPOSE_VOICEMAIL_SUCCESS = 'COMPOSE_VOICEMAIL_SUCCESS';

//Org Employees
export const ORG_EMP_LIST = 'ORG_EMP_LIST';
export const ORG_EMP_LIST_SUCCESS = 'ORG_EMP_LIST_SUCCESS';
export const ADD_ORG_EMPLOYEES = 'ADD_ORG_EMPLOYEES';
export const ADD_ORG_EMPLOYEES_SUCCESS = 'ADD_ORG_EMPLOYEES_SUCCESS';
export const EDIT_ORG_EMPLOYEES = 'EDIT_ORG_EMPLOYEES';
export const CHANGE_EMAIL_REQUEST_ADD = 'CHANGE_EMAIL_REQUEST_ADD';
export const CHANGE_EMAIL_REQUEST_ADD_SUCCESS = 'CHANGE_EMAIL_REQUEST_ADD_SUCCESS';
export const UNIQUE_CODE_VERIFICATION = 'UNIQUE_CODE_VERIFICATION';
export const UNIQUE_CODE_VERIFICATION_SUCCESS = 'UNIQUE_CODE_VERIFICATION_SUCCESS';

//Notification Types
export const ADD_NOTIFI_TYPES = 'ADD_NOTIFI_TYPES';
export const ADD_NOTIFI_TYPES_SUCCESS = 'ADD_NOTIFI_TYPES_SUCCESS';
export const NOTIFI_TYPES_LIST = 'NOTIFI_TYPES_LIST';
export const NOTIFI_TYPES_LIST_SUCCESS = 'NOTIFI_TYPES_LIST_SUCCESS';
export const NOTIFI_TYPES_STATUS_CHANGE = 'NOTIFI_TYPES_STATUS_CHANGE';
export const EDIT_NOTIFI_TYPES = 'EDIT_NOTIFI_TYPES';

// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

//Contact Module const
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

//Auth const
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNIN_GOOGLE_USER = 'SIGNIN_GOOGLE_USER';
export const SIGNIN_GOOGLE_USER_SUCCESS = 'SIGNIN_GOOGLE_USER_SUCCESS';
export const SIGNIN_FACEBOOK_USER = 'SIGNIN_FACEBOOK_USER';
export const SIGNIN_FACEBOOK_USER_SUCCESS = 'SIGNIN_FACEBOOK_USER_SUCCESS';
export const SIGNIN_TWITTER_USER = 'SIGNIN_TWITTER_USER';
export const SIGNIN_TWITTER_USER_SUCCESS = 'SIGNIN_TWITTER_USER_SUCCESS';
export const SIGNIN_GITHUB_USER = 'SIGNIN_GITHUB_USER';
export const SIGNIN_GITHUB_USER_SUCCESS = 'signin_github_user_success';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';
export const USER_DATA = 'user_data';
export const USER_TOKEN_SET = 'user_token_set';
export const RESEND_EMAIL = 'RESEND_EMAIL';
export const RESEND_EMAIL_DATA = 'RESEND_EMAIL_DATA';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_DATA = 'RESET_PASSWORD_DATA';


export const ACTIVATION_STATUS_SUCCESS = 'ACTIVATION_STATUS_SUCCESS';
export const CHANGE_PASSWORD_RESPONSE = 'CHANGE_PASSWORD_RESPONSE';
export const CHANGE_PSW = 'CHANGE_PSW';
export const REGISTER_PSW_SUCCESS = 'REGISTER_PSW_SUCCESS';
export const USER_DATA_GET = 'USER_DATA_GET';
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';
export const ACTIVATION_STATUS_CHECK = 'ACTIVATION_STATUS_CHECK';
export const REGISTER_PSW = 'REGISTER_PSW';

//Subscribers
export const ADD_SUBSCRIBER = 'ADD_SUBSCRIBER';
export const ADD_SUBSCRIBER_SUCCESS = 'ADD_SUBSCRIBER_SUCCESS';
export const SUBSCRIBERS_LIST_SERVICE ='SUBSCRIBERS_LIST_SERVICE';
export const SUBSCRIBERS_LIST_SERVICE_SUCCESS='SUBSCRIBERS_LIST_SERVICE_SUCCESS';
export const EDIT_SUBSCRIBER='EDIT_SUBSCRIBER';
export const EDIT_SUBSCRIBER_SUCCESS='EDIT_SUBSCRIBER_SUCCESS';
export const SUBSCRIBE_SINGLE_VIEW_LIST = 'SUBSCRIBE_SINGLE_VIEW_LIST' ;
export const SUBSCRIBE_SINGLE_VIEW_LIST_SUCCESS = 'SUBSCRIBE_SINGLE_VIEW_LIST_SUCCESS' ;

//SuperAdmin 
export const ADD_SITEADMIN_USERS = 'ADD_SITEADMIN_USERS';
export const EDIT_SITEADMIN_USERS = 'EDIT_SITEADMIN_USERS';
export const EDIT_SITEADMIN_USERS_SUCCESS = 'EDIT_SITEADMIN_USERS_SUCCESS';
export const ADD_SITEADMIN_USERS_SUCCESS = 'ADD_SITEADMIN_USERS_SUCCESS';
export const SITE_ADMIN_USERS_LIST = 'SITE_ADMIN_USERS_LIST';
export const SITE_ADMIN_USERS_LIST_SUCCESS = 'SITE_ADMIN_USERS_LIST_SUCCESS';

//SiteAdmin
export const ADD_ORGADMIN_USERS = 'ADD_ORGADMIN_USERS';
export const ADD_ORGADMIN_USERS_SUCCESS = 'ADD_ORGADMIN_USERS_SUCCESS';
export const EDIT_ORGADMIN_USERS = 'EDIT_ORGADMIN_USERS';
export const EDIT_ORGADMIN_USERS_SUCCESS = 'EDIT_ORGADMIN_USERS_SUCCESS';
export const ORG_ADMIN_DETAILS_GET = 'ORG_ADMIN_DETAILS_GET';
export const ORG_ADMIN_DETAILS_GET_SUCCESS = 'ORG_ADMIN_DETAILS_GET_SUCCESS';
export const ORG_ADMIN_USERS_LIST = 'ORG_ADMIN_USERS_LIST';
export const ORG_ADMIN_USERS_LIST_SUCCESS = 'ORG_ADMIN_USERS_LIST_SUCCESS';

//Groups
export const ADD_GROUP = 'ADD_GROUP';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const GROUP_LIST_SERVICE ='GROUP_LIST_SERVICE';
export const GROUP_LIST_SERVICE_SUCCESS='GROUP_LIST_SERVICE_SUCCESS';
export const EDIT_GROUP='EDIT_GROUP';
export const EDIT_GROUP_SUCCESS='EDIT_GROUP_SUCCESS';
export const GROUP_STATUS_CHANGE='GROUP_STATUS_CHANGE';
export const GROUP_DATA_GET_SERVICE='GROUP_DATA_GET_SERVICE';
export const GROUP_DATA_GET_SERVICE_SUCCESS='GROUP_DATA_GET_SERVICE_SUCCESS';
export const REMOVE_SUBSCRIBER_FROM_GROUP='REMOVE_SUBSCRIBER_FROM_GROUP';
export const REMOVE_SUBSCRIBER_FROM_GROUP_SUCCESS='REMOVE_SUBSCRIBER_FROM_GROUP_SUCCESS';

// History
export const COMPOSE_HISTORY_LIST_ACTION = 'COMPOSE_HISTORY_LIST_ACTION';
export const COMPOSE_HISTORY_LIST_SUCCESS = 'COMPOSE_HISTORY_LIST_SUCCESS';

//DashBoards Related Actions 


export const SITE_ADMIN_DASHBOARD_LIST_SUCCESS = 'SITE_ADMIN_DASHBOARD_LIST_SUCCESS';
export const SITE_ADMIN_DASHBOARD_LIST_ERROR = 'SITE_ADMIN_DASHBOARD_LIST_ERROR';
export const SITE_ADMIN_DASHBOARD_LIST_ACTION = 'SITE_ADMIN_DASHBOARD_LIST';
export const SITE_ADMIN_DASHBOARD_LIST_COUNT = 'SITE_ADMIN_DASHBOARD_LIST_COUNT'; 

export const ORG_ADMIN_DASHBOARD_LIST_SUCCESS = 'ORG_ADMIN_DASHBOARD_LIST_SUCCESS';
export const ORG_ADMIN_DASHBOARD_LIST_ERROR = 'ORG_ADMIN_DASHBOARD_LIST_ERROR';
export const ORG_ADMIN_DASHBOARD_LIST_ACTION = 'ORG_ADMIN_DASHBOARD_LIST';
export const ORG_ADMIN_DASHBOARD_LIST_COUNT = 'ORG_ADMIN_DASHBOARD_LIST_COUNT'; 

export const ORG_EMPLOYEE_DASHBOARD_LIST_SUCCESS = 'ORG_EMPLOYEE_DASHBOARD_LIST_SUCCESS';
export const ORG_EMPLOYEE_DASHBOARD_LIST_ERROR = 'ORG_EMPLOYEE_DASHBOARD_LIST_ERROR';
export const ORG_EMPLOYEE_DASHBOARD_LIST_ACTION = 'ORG_EMPLOYEE_DASHBOARD_LIST';
export const ORG_EMPLOYEE_DASHBOARD_LIST_COUNT = 'ORG_EMPLOYEE_DASHBOARD_LIST_COUNT'; 

export const ORG_SCOPE_EMPLOYEE_DASHBOARD_LIST_ACTION ="ORG_SCOPE_EMPLOYEE_DASHBOARD_LIST_ACTION" ;
export const ORG_SCOPE_EMPLOYEE_DASHBOARD_LIST_SUCCESS = "ORG_SCOPE_EMPLOYEE_DASHBOARD_LIST_SUCCESS" ;
export const ORG_SCOPE__EMPLOYEE_DASHBOARD_LIST_ERROR = "ORG_SCOPE__EMPLOYEE_DASHBOARD_LIST_ERROR" ;

export const SUBSCRIBERS_DASHBOARD_LIST_SUCCESS = 'SUBSCRIBERS_DASHBOARD_LIST_SUCCESS';
export const SUBSCRIBERS_DASHBOARD_LIST_ERROR = 'SUBSCRIBERS_DASHBOARD_LIST_ERROR';
export const SUBSCRIBERS_DASHBOARD_LIST_ACTION = 'SUBSCRIBERS_DASHBOARD_LIST';
export const SUBSCRIBERS_DASHBOARD_LIST_COUNT = 'SUBSCRIBERS_DASHBOARD_LIST_COUNT'; 

export const GROUP_DASHBOARD_LIST_SUCCESS = 'GROUP_DASHBOARD_LIST_SUCCESS';
export const GROUP_DASHBOARD_LIST_ERROR = 'GROUP_DASHBOARD_LIST_ERROR';
export const GROUP_DASHBOARD_LIST_ACTION = 'GROUP_DASHBOARD_LIST';
export const GROUP_DASHBOARD_LIST_COUNT = 'GROUP_DASHBOARD_LIST_COUNT'; 

export const NOTIFICATION_DASHBOARD_LIST_SUCCESS = 'NOTIFICATION_DASHBOARD_LIST_SUCCESS';
export const NOTIFICATION_DASHBOARD_LIST_ERROR = 'NOTIFICATION_DASHBOARD_LIST_ERROR';
export const NOTIFICATION_DASHBOARD_LIST_ACTION = 'NOTIFICATION_DASHBOARD_LIST_ACTION';
export const NOTIFICATION_DASHBOARD_LIST_COUNT = 'NOTIFICATION_DASHBOARD_LIST_COUNT'; 

export const NOTIFICATION_LIST_SUCCESS = "NOTIFICATION_LIST_SUCCESS";
export const NOTIFICATION_GET_LIST_REQUEST = "NOTIFICATION_GET_LIST_REQUEST";
export const NOTIFICATION_GET_LIST_SUCCESS = "NOTIFICATION_GET_LIST_SUCCESS";

//Subscribers Group List

export const GROUPS_LIST = 'GROUPS_LIST';
export const GROUPS_LIST_SUCCESS = 'GROUPS_LIST_SUCCESS';

//Subscriners Groups Edit

export const GROUP_MAPPED_ADD_SERVICE = 'GROUP_MAPPED_ADD_SERVICE';
export const GROUP_MAPPED_ADD_SERVICE_SUCCESS = 'GROUP_MAPPED_ADD_SERVICE_SUCCESS';

export const CHANGE_SUBSCRIBER_GET_REQUEST = "CHANGE_SUBSCRIBER_GET_REQUEST";
export const CHANGE_SUBSCRIBER_GET_SUCCESS  = "CHANGE_SUBSCRIBER_GET_SUCCESS";


// For subscribe data in org admin and employee
export const SUBSCRIBE_LIST_DATA = 'SUBSCRIBE_LIST_DATA';
export const SUBSCRIBE_LIST_DATA_SUCCESS = 'SUBSCRIBE_LIST_DATA_SUCCESS';
export const SUBSCRIBE_LIST_UPDATE_DATA = 'SUBSCRIBE_LIST_UPDATE_DATA'; 
export const SUBSCRIBE_LIST_UPDATE_DATA_SUCCESS = 'SUBSCRIBE_LIST_UPDATE_DATA_SUCCESS';


export const CHANGE_MOBILE_REQUEST_ADD = "CHANGE_MOBILE_REQUEST_ADD";
export const CHANGE_MOBILE_REQUEST_ADD_SUCCESS = "CHANGE_MOBILE_REQUEST_ADD_SUCCESS";
export const UNIQUE_MOBILE_CODE_VERIFICATION = "UNIQUE_MOBILE_CODE_VERIFICATION";
export const UNIQUE_MOBILE_CODE_VERIFICATION_SUCCESS = "UNIQUE_MOBILE_CODE_VERIFICATION_SUCCESS";
export const EDIT_NOTIFI_TYPES_SUCCESS = "EDIT_NOTIFI_TYPES_SUCCESS";

